name: Continuous Integration

on:
  push:
    branches:
      - develop
      - main
        tags-ignore:
          - '*'

jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: './src/Fort.sln'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Build
        run: dotnet build $SOLUTION --configuration $BUILD_CONFIG

      - name: Test
        run: dotnet tets $SOLUTION