name: 'Continuous Deployment'

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Get Nuget Version
        run: echo "app_version=`git describe --tags`" >> $GITHUB_ENV
      - name: Get Release Status
      - name: Build
      - name: Test
      - name: Pack
      - name: Publish
        run: 