name: 'Continuous Deployment'

on:
  push:
    tags:
      - '*'

jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: './src/Fort.sln'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Get Nuget Version
        run: echo "APP_VERSION=`git describe --tags`" >> $GITHUB_ENV

      - name: Get Release Status
        run: echo "APP_RELEASE=`(git describe --tags --exact-match>/dev/null 2>&1 && echo true) || echo false`" >> $GITHUB_ENV

      - name: Build
        run: dotnet build $SOLUTION --configuration Release -p:Version=$APP_VERSION

      - name: Test
        run: dotnet test $SOLUTION

      - name: Pack
        run: |
          dotnet pack $SOLUTION --configuration Release -p:Version=$APP_VERSION --output nuget-packages --include-symbols --include-source -p:SymbolPackageFormat=snupkg

      - name: List Packages
        run: ls ./nuget-packages

      - name: Publish
        run: dotnet nuget push nuget-packages/*.* --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate true --source https://api.nuget.org/v3/index.json 