name: 'Continuous Deployment'

on:
  push:
    tags:
      - '*'

jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: './src/Fort.sln'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup .NET 7
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Get Nuget Version
        run: echo "APP_VERSION=`git describe --tags`" >> $GITHUB_ENV

      - name: Get Release Status
        run: echo "APP_RELEASE=`(git describe --tags --exact-match>/dev/null 2>&1 && echo true) || echo false`" >> $GITHUB_ENV

      - name: Build
        run: dotnet build $SOLUTION --configuration Release -p:Version=$APP_VERSION

      - name: Test
        run: dotnet test $SOLUTION

      - name: Pack
        run: |
          dotnet pack $SOLUTION --configuration Release -p:Version=$APP_VERSION --output nuget-packages --include-source

      - name: List Packages
        run: ls ./nuget-packages

      - name: Add GitHub Packages
        run: dotnet nuget add source --username chrris99 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/chrris99/index.json"
      
      - name: Publish Nuget
        run: dotnet nuget push nuget-packages/*.nupkg  --api-key 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 --source "github"